//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NWIND_PROY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public long PKUsuarioId { get; set; }
        public string Usuario { get; set; }
        public string UsuarioNombre { get; set; }
        public string Contrasenia { get; set; }
        public long FKPerfilId { get; set; }
    
        public virtual Perfiles Perfiles { get; set; }
    }
}
